version: '3.8'

services:
  postgres:
    image: postgres:16.1-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_service
    ports:
      - 5432:5432
    volumes:
      - distribued_shop:/var/lib/postgresql/data
    networks:
      - distribued_shop
  rabbitmq:
    image: rabbitmq:3.8.9-management-alpine
    hostname: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: 'SWQOKODSQALRPCLNMEQG'
      RABBITMQ_DEFAULT_USER: 'rabbit'
      RABBITMQ_DEFAULT_PASS: 'rabbit'
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  distribued_shop:

networks:
  distribued_shop:
    driver: bridge